### ISSUE TITLE
click on one checkbox fires all on the page

### ISSUE THREAD

**Issue by joshua1** [yiller/ng4-icheck#1]
click on one checkbox, triggers all checkboxes on the page instead of the one clicked

**Comment by yiller** [comment]
please upgrade to 1.1.0. 
1. one icheck component need one wrapper container(div or label), please check demo or readme;
&lt;label&gt;&lt;input icheck type="checkbox"&gt; Click here to toggle checkbox &lt;/label&gt;
&lt;div&gt;&lt;input icheck type="checkbox"&gt;&lt;label&gt;Click here to toggle checkbox&lt;/label&gt;&lt;/div&gt;
2. This problem is because the style of the wrapper element lack "position", you can add "position: relative;" or "position:absolute;" to div( or label) for fixing. Or upgrading to 1.1.0 via "npm install angular4-icheck@1.1.0 --save";

请升级到1.1.0.
1. 一个 icheck 组件需要有一个外层容器（div或者label）,具体的你可以参考demo或者readme档，例如：
&lt;label&gt;&lt;input icheck type="checkbox"&gt; Click here to toggle checkbox &lt;/label&gt;
&lt;div&gt;&lt;input icheck type="checkbox"&gt;&lt;label&gt;Click here to toggle checkbox&lt;/label&gt;&lt;/div&gt;
2. 导致这个问题的原因是由于外层元素缺少position样式导致的，你可以在外层元素（div或者label）上增加 position: relative; 或者 position: absolute; 的样式规则。你也可以选择直接通过npm更新到1.1.0版本，会默认为外层元素增加 position:relative; 的样式规则，如果你的DOM环境需要其他的定位方案，你可以增加 position: absolute !important;
